builders:
  graphql:
    import: "package:graphql3_generator/graphql3_generator.dart"
    builder_factories:
      - graphQLBuilder
    auto_apply: root_package
    build_to: cache
    build_extensions:
      .dart:
        - graphql3_generator.g.part
    required_inputs:
      - angel3_serialize.g.part
    applies_builders:
      - source_gen|combining_builder