name: graphql_generator
version: 2.0.0
description: Generates GraphQL schemas from Dart classes, for use with pkg:graphql_server.
homepage: https://github.com/angel-dart/graphql
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  analyzer: ^1.7.0
  angel_model:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/model
  angel_serialize_generator:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/serialize/angel_serialize_generator
  graphql_schema:
    git: 
      url: https://github.com/dukefirehawk/graphql_dart.git
      ref: sdk-2.12.x_nnbd
      path: graphql_schema
  build: ^2.0.2
  build_config: ^1.0.0
  code_builder: ^4.0.0
  recase: ^4.0.0
  source_gen: ^1.0.2
  collection: ^1.15.0-nullsafety.4
dev_dependencies:
  build_runner: ^2.0.4
  pedantic: ^1.11.0