name: graphql_data_loader2
version: 2.0.0
description: Batch and cache database lookups. Works well with GraphQL. Ported from JS.
homepage: https://github.com/dukefirehawk/graphql_dart/tree/master/graphql_data_loader
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  graphql_schema:
    git: 
      url: https://github.com/dukefirehawk/graphql_dart.git
      ref: sdk-2.12.x_nnbd
      path: graphql_schema
  pedantic: ^1.11.0
  test: ^1.17.7